actions:
  - danger_level: high
    type: confirm
    message: "This is a high danger operation. Proceed? (y/n): "
  - danger_level: medium
    type: timeout
    message: "This is a medium danger operation. Proceeding in 5 seconds."
    timeout: 5
  - danger_level: low
    type: force
    message: "This is a low danger operation."

tools:
  - name: kubectl
    command:
      - kubectl
    params:
      namespace:
        description: The namespace to run the command in
        type: string
        required: true
        validate:
          - danger_level: high
            exclude:
              - kube-system
              - kube-public
              - default
    subtools:
      - name: get pod
        args: ["get", "pod", "-o", "json", "-n", "{{.namespace}}"]
      - name: describe pod
        params:
          pod:
            description: The pod to describe
            type: string
            required: true
        args: ["describe", "pod", "{{.pod}}", "-n", "{{.namespace}}"]
      - name: delete pod
        danger_level: high
        params:
          pod:
            description: The pod to delete
            type: string
            required: true
        args: ["delete", "pod", "{{.pod}}", "-n", "{{.namespace}}"]
  
  - name: echo
    command:
      - echo
    params:
      message:
        description: The message to echo
        type: string
        required: true
    subtools:
      - name: hello
        args: ["Hello, {{.message}}!"]
      - name: goodbye
        args: ["Goodbye, {{.message}}!"]