name: E2E Tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  e2e-test:
    name: Run E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: true

      - name: Build application
        run: make build

      - name: Run E2E tests
        run: bash ./misc/run_e2e_test.sh
        
      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: operations-binary
          path: build/operations
