name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          cache: true

      - name: Install golint
        run: go install golang.org/x/lint/golint@latest

      - name: Run go fmt
        run: |
          go fmt ./...
          if [ "$(git status --porcelain | wc -l)" -gt 0 ]; then
            echo "Code is not formatted. Please run 'go fmt ./...'"
            git status --porcelain
            exit 1
          fi

      - name: Run go vet
        run: go vet ./...

      - name: Run golint
        run: golint -set_exit_status ./...

      - name: Run unit tests
        run: make test

      - name: Run test with coverage
        run: make test-coverage

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage.html